"""
Identify the specific bugs causing wrong P&L calculations
"""

print("=" * 80)
print("BUG ANALYSIS: Short Call P&L = $119 instead of $142")
print("=" * 80)
print()
print("SCENARIO:")
print("  - Sell short call for $142 premium on Monday")
print("  - Strike: $618")
print("  - SPY closes Friday at $610.18 (OTM by $7.82)")
print("  - DTE on Friday: 0 (option expires)")
print()
print("EXPECTED:")
print("  - Option expires worthless (OTM)")
print("  - P&L = $142 (keep full premium)")
print()
print("ACTUAL:")
print("  - P&L shown = $119")
print("  - Missing: $23")
print()
print("=" * 80)
print("BUG #1: NO AUTO-CLOSE ON EXPIRATION")
print("=" * 80)
print()
print("CODE: stateManager.ts lines 166-177")
print("""
// Check for expiration
if (newDte <= 0) {
  // Option expired - handle assignment
  if (newMarket.spyPrice > state.shortCall.strike) {
    console.warn('Short call expired ITM - assignment required');
  } else {
    console.log('Short call expired OTM - full profit captured');
  }
}
""")
print("PROBLEM:")
print("  - Code logs expiration but DOESN'T actually close the position!")
print("  - Option with DTE=0 still has some calculated value (~$20-23)")
print("  - Should force currentValue = 0 and auto-close")
print()
print("CALCULATION:")
print("  - weekStartValue = $142")
print("  - currentValue = $23 (BUG: should be $0)")
print("  - P&L = $142 - $23 = $119 ✗")
print()
print("SHOULD BE:")
print("  - weekStartValue = $142")
print("  - currentValue = $0 (expired OTM)")
print("  - P&L = $142 - $0 = $142 ✓")
print()
print()

print("=" * 80)
print("BUG #2: WEEK START VALUE CALCULATION")
print("=" * 80)
print()
print("CODE: stateManager.ts lines 189-194")
print("""
const newShortCallWeekStartValue = isNewWeek && state.shortCall
  ? state.shortCall.currentValue  // OLD value before today's update
  : state.shortCallWeekStartValue;
""")
print("PROBLEM:")
print("  - At the start of a new week (e.g., Monday of Week 2)")
print("  - Sets weekStartValue to FRIDAY's closing value from Week 1")
print("  - But the position might have been rolled or changed!")
print()
print("EXAMPLE:")
print("  Week 1 Friday: Short call value = $20")
print("  Week 2 Monday: New short call opened for $157")
print("  Week 2 start value set to: $20 (WRONG!)")
print("  Should be: $157")
print()
print()

print("=" * 80)
print("BUG #3: LEAPS P&L CALCULATION")
print("=" * 80)
print()
print("SCENARIO:")
print("  - SPY drops $5.51 (from $615.68 to $610.18)")
print("  - LEAPS has 88% delta")
print("  - Theta = -1.31/day (shown)")
print()
print("DISPLAY SHOWS:")
print("  Stock Impact: -$5.51 × 88% = $-485")
print("  Time Decay: -1.31/day × 7 = $-21")
print()
print("BUG IN CALCULATION:")
print("  1. Stock Impact formula: priceChange × delta × 100")
print("     -5.51 × 0.88 × 100 = -485 ✓")
print()
print("  2. Time Decay: theta × 7")
print("     -1.31 × 7 = -9.17")
print("     BUT display shows -21!")
print()
print("  DIAGNOSIS:")
print("    - Either the actual theta is -3 (not -1.31 as shown)")
print("    - Or there's a calculation/display mismatch")
print()
print("  3. User says actual P&L should be +$405, not -$563")
print("     That's a $968 error!")
print()
print("  LIKELY CAUSE:")
print("    - Week start value is wrong (same bug as short call)")
print("    - Using wrong baseline for weekly calculation")
print()
print()

print("=" * 80)
print("SOLUTIONS")
print("=" * 80)
print()
print("FIX #1: Auto-close expired options")
print("  - When DTE <= 0 and OTM, set currentValue = 0")
print("  - Auto-close the position and realize P&L")
print()
print("FIX #2: Reset week start value on position open/roll")
print("  - When selling a new short call, set weekStartValue = premium")
print("  - Don't inherit from previous week's closing value")
print("  - stateManager.ts line 250 already does this correctly!")
print("  - The bug is in line 193 overwriting it on new week start")
print()
print("FIX #3: Verify LEAPS week start value")
print("  - Same issue as short call")
print("  - Week start should be when position is opened, not Friday")
print()
print("=" * 80)
